# Change these first
owner: o3o-ca # Your GitHub organization or username, where this repository lives
repo: o3o-uptime # The name of this repository

sites:
  - name: O3O.ca (Mastodon)
    url: https://o3o.ca
  - name: Mastodon.im (Mastodon)
    url: https://mastodon.im
  - name: Writee (Writefreely)
    url: https://writee.org
  - name: O3O Cafe (Matrix)
    check: "tcp-ping"
    url: matrix.o3o.cafe
    port: 443
  - name: Blog.edu.kg (WordPress)
    url: https://blog.edu.kg
  - name: o3o.foundation
    url: https://o3o.foundation

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.o3o.foundation
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: O3O 服务状态监控页
  introTitle: "O3O.Foundation 是位于加拿大的非盈利服务，我们主要为全球的中文用户服务。我们相信由社会组织运营基本通讯软件和设施是必要的，它们不应被控制在大型企业和政府手中。"
  introMessage: "[O3O.Foundation](https://o3o.foundation/) is a non-profit online service based in Canada. We serve primarily Chinese language users worldwide by providing privacy-conscious services and tools. We believe that it is necessary for social organizations to operate communication platforms and infrastructure, and that they should not be controlled by large corporations and governments."
  navbar:
    - title: Home
      href: https://o3o.foundation/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
